from flask import Flask

from get_all_ratings_of_vendor import get_all_ratings_of_current_vendor_id
from get_avg_ratings_of_vendor import get_average_ratings_of_current_vendor_id
from get_order_details_by_order_id import get_order_details_of_order_id
from get_order_details_of_user import get_order_details_of_user
from get_ratings_of_product import vendor_ratings_of_current_product
from get_wishlist_items import get_items_of_user_in_wishlist

app = Flask(__name__)
